# Scenario leak: one client process opens and closes a singleplayer world with three vessels near spawn several times,
# flying them each time. After every close no Jolt engine or body may remain alive (native handles are freed on level
# unload), and heap after garbage collection and the process's private memory must not keep growing cycle after cycle.
# The singleplayer world is generated by the dedicated server (which is stopped for the test and restarted by the next
# scenario that needs it).
param([int]$Cycles = 5, [switch]$StopAfter)
. (Join-Path $PSScriptRoot '..\..\scenarios\_common.ps1')

$session = Start-SlipwayE2ESession
$s = $session.Server; $c = $session.Client
$run = New-SlipwayE2ERun -Name 'leak'
$clientOffset = Get-SlipwayE2ELogOffset -LogPath $c.ClientLog
$serverOffset = Get-SlipwayE2ELogOffset -LogPath $s.LogPath
$saveName = 'slipway-leak'

function Wait-Agent([scriptblock]$Until, [int]$Seconds, [string]$What) {
	$deadline = (Get-Date).AddSeconds($Seconds)
	do {
		$value = try { & $Until } catch { $null }
		if ($value) { return $value }
		Start-Sleep -Milliseconds 500
	} while ((Get-Date) -lt $deadline)
	throw "Timed out waiting for $What"
}
function Get-Natives {
	$t = [string](Invoke-SlipwayE2EAgent -Client $c -Verb slipway -Argument 'natives')
	$m = [regex]::Match($t, 'engines=(\d+) bodies=(\d+) managers=(\d+) clientVessels=(\d+)')
	[pscustomobject]@{ Engines = [int]$m.Groups[1].Value; Bodies = [int]$m.Groups[2].Value; Managers = [int]$m.Groups[3].Value; ClientVessels = [int]$m.Groups[4].Value; Text = $t }
}
function Get-Memory {
	$t = [string](Invoke-SlipwayE2EAgent -Client $c -Verb mem)
	$p = Get-Process -Id $c.ProcessId
	$o = [ordered]@{ Text = $t; PrivateMb = [Math]::Round($p.PrivateMemorySize64 / 1MB, 1); WorkingSetMb = [Math]::Round($p.WorkingSet64 / 1MB, 1) }
	foreach ($m in [regex]::Matches($t, '(\w+)=([\d.]+)')) { $o[$m.Groups[1].Value] = [double]$m.Groups[2].Value }
	[pscustomobject]$o
}

try {
	# 1. A small world with three assembled vessels hovering near spawn.
	Invoke-SlipwayE2EAgent -Client $c -Verb disconnect | Out-Null
	Stop-SlipwayE2EServer -Server $s | Out-Null
	New-SlipwayE2EWorld -Name 'leak-sp' | Out-Null
	$ls = Start-SlipwayE2EServer -World 'leak-sp'
	$serverOffset = 0
	Send-SlipwayE2ERcon -Command 'forceload add -48 -16 48 48' | Out-Null
	Start-Sleep -Seconds 3
	Send-SlipwayE2ERcon -Command 'fill -8 99 -8 8 99 -2 minecraft:glass' | Out-Null
	$ids = @()
	foreach ($k in 0..2) {
		$x = -14 + 14 * $k; $z = 16
		Send-SlipwayE2ERcon -Command ("fill {0} 99 {1} {2} 99 {3} minecraft:oak_planks" -f ($x - 2), ($z - 2), ($x + 2), ($z + 2)) | Out-Null
		Send-SlipwayE2ERcon -Command ("setblock {0} 100 {1} slipway:helm[facing=north]" -f $x, $z) | Out-Null
		Send-SlipwayE2ERcon -Command ("setblock {0} 100 {1} minecraft:chest" -f ($x + 1), ($z + 1)) | Out-Null
		$ids += Invoke-SlipwayE2EAssembleCommand -X $x -Y 100 -Z $z
	}
	Send-SlipwayE2ERcon -Command 'forceload remove all' | Out-Null
	Add-SlipwayE2ECheck -Run $run -Title 'the test world has three vessels' -Condition ($ids.Count -eq 3) -Detail ("vessels " + ($ids -join ', ')) | Out-Null
	Stop-SlipwayE2EServer -Server $ls | Out-Null

	# 2. Into the client's saves, as a creative world with cheats.
	$dest = Join-Path $c.GameDir "saves\$saveName"
	if (Test-Path $dest) { Remove-Item $dest -Recurse -Force }
	Copy-Item (Join-Path (Get-SlipwayE2EServerDir) 'leak-sp') $dest -Recurse
	Remove-Item (Join-Path $dest 'session.lock') -Force -ErrorAction SilentlyContinue
	@'
import sys, nbtlib
f = nbtlib.load(sys.argv[1])
d = f["Data"]
d["allowCommands"] = nbtlib.Byte(1)
d["GameType"] = nbtlib.Int(1)
d["LevelName"] = nbtlib.String("Slipway leak test")
f.save()
print("level.dat updated")
'@ | python - (Join-Path $dest 'level.dat') | Out-Null

	# 3. Open, fly, close; several times, with JFR sampling old objects and their paths to GC roots.
	$jdk = "$env:USERPROFILE\.jdks\jdk-25.0.3+9\bin"
	$jfr = Join-Path $run.Directory 'leak.jfr'
	& "$jdk\jcmd.exe" $c.ProcessId JFR.start name=slipwayleak settings=profile path-to-gc-roots=true 2>&1 | Out-Null
	$rows = [System.Collections.Generic.List[object]]::new()
	for ($cycle = 1; $cycle -le $Cycles; $cycle++) {
		Invoke-SlipwayE2EAgent -Client $c -Verb openworld -Argument $saveName | Out-Null
		Wait-Agent { $w = Invoke-SlipwayE2EAgent -Client $c -Verb session; $sc = Invoke-SlipwayE2EAgent -Client $c -Verb screen; ($w -like 'world singleplayer*') -and $sc -eq 'none' } 180 'the world to open' | Out-Null
		Invoke-SlipwayE2EAgent -Client $c -Verb chat -Argument '/tp @s 0 100.5 -5' | Out-Null
		Wait-Agent { $v = [string](Invoke-SlipwayE2EAgent -Client $c -Verb slipway -Argument 'vessels'); ([regex]::Matches($v, 'ready=true').Count -ge 3) } 60 'the vessels to arrive' | Out-Null
		$open = Get-Natives
		# 200 ticks: the input must still be on when the speeds are read 5 s later (100 ticks ended right at the read).
		foreach ($id in $ids) { Invoke-SlipwayE2EAgent -Client $c -Verb chat -Argument "/slipway control $id 0.3 0 0.1 0 0.4 0 200" | Out-Null }
		Start-Sleep -Seconds 5
		$flying = Get-Natives
		$vessels = [string](Invoke-SlipwayE2EAgent -Client $c -Verb slipway -Argument 'vessels')
		$speeds = @([regex]::Matches($vessels, 'speed=([\d.]+)') | ForEach-Object { [double]$_.Groups[1].Value })
		Invoke-SlipwayE2EAgent -Client $c -Verb disconnect | Out-Null
		Wait-Agent { (Invoke-SlipwayE2EAgent -Client $c -Verb session) -like 'title*' } 120 'the world to close' | Out-Null
		Start-Sleep -Seconds 3
		$closed = Get-Natives
		$mem = Get-Memory
		# Live-object histogram (forces a full GC) so any growth can be traced to the classes that grow.
		$histogram = Join-Path $run.Directory ("histogram-cycle{0}.txt" -f $cycle)
		& "$env:USERPROFILE\.jdks\jdk-25.0.3+9\bin\jcmd.exe" $c.ProcessId GC.class_histogram 2>&1 | Set-Content $histogram
		$row = [pscustomobject]@{ Cycle = $cycle; OpenEngines = $open.Engines; OpenBodies = $open.Bodies; FlyingBodies = $flying.Bodies
			MaxSpeed = ($speeds | Measure-Object -Maximum).Maximum; ClosedEngines = $closed.Engines; ClosedBodies = $closed.Bodies; ClosedManagers = $closed.Managers; ClosedClientVessels = $closed.ClientVessels
			HeapUsedMb = $mem.heapUsedMb; DirectMb = $mem.directMb; PrivateMb = $mem.PrivateMb; WorkingSetMb = $mem.WorkingSetMb }
		$rows.Add($row)
		$run.Notes.Add(("cycle {0}: open engines={1} bodies={2}; flying bodies={3} max speed {4:N2}; closed engines={5} bodies={6}; heap after GC {7:N1} MB, direct {8:N1} MB, process private {9:N1} MB, working set {10:N1} MB" -f `
			$cycle, $row.OpenEngines, $row.OpenBodies, $row.FlyingBodies, $row.MaxSpeed, $row.ClosedEngines, $row.ClosedBodies, $row.HeapUsedMb, $row.DirectMb, $row.PrivateMb, $row.WorkingSetMb))
	}
	$rows | ConvertTo-Json | Set-Content (Join-Path $run.Directory 'leak.json')
	# Which classes grew between the second and the last cycle (live objects after full GCs)?
	$parse = {
		param($path)
		$map = @{}
		foreach ($line in Get-Content $path) {
			if ($line -match '^\s*\d+:\s+(\d+)\s+(\d+)\s+(\S+)') { $map[$matches[3]] = @([long]$matches[1], [long]$matches[2]) }
		}
		$map
	}
	$h2 = & $parse (Join-Path $run.Directory 'histogram-cycle2.txt')
	$hN = & $parse (Join-Path $run.Directory ("histogram-cycle{0}.txt" -f $Cycles))
	$growth = foreach ($k in $hN.Keys) {
		$before = if ($h2.ContainsKey($k)) { $h2[$k] } else { @(0, 0) }
		[pscustomobject]@{ Class = $k; Instances = $hN[$k][0] - $before[0]; Mb = [Math]::Round(($hN[$k][1] - $before[1]) / 1MB, 2) }
	}
	$top = $growth | Sort-Object Mb -Descending | Select-Object -First 20
	$top | Format-Table -AutoSize | Out-String -Width 200 | Set-Content (Join-Path $run.Directory 'histogram-growth.txt')
	$run.Notes.Add("largest growth, cycle 2 -> ${Cycles}: " + (($top | Select-Object -First 8 | ForEach-Object { "$($_.Class) +$($_.Mb) MB (+$($_.Instances))" }) -join '; '))
	$worlds = foreach ($k in 'net.minecraft.server.level.ServerLevel', 'net.minecraft.client.multiplayer.ClientLevel', 'net.minecraft.world.level.chunk.LevelChunk',
		'net.minecraft.server.MinecraftServer', 'net.minecraft.client.server.IntegratedServer') {
		"{0}: {1} -> {2}" -f ($k -replace '^.*\.', ''), $(if ($h2.ContainsKey($k)) { $h2[$k][0] } else { 0 }), $(if ($hN.ContainsKey($k)) { $hN[$k][0] } else { 0 })
	}
	$slipway = @($growth | Where-Object { $_.Class -match 'slipway|joltjni' -and $_.Instances -gt 0 } | Sort-Object Mb -Descending | Select-Object -First 8 | ForEach-Object { "$($_.Class) +$($_.Instances)" })
	$run.Notes.Add("live instances at the title screen, cycle 2 -> ${Cycles}: " + ($worlds -join '; ') + "; Slipway/jolt classes that grew: " + $(if ($slipway.Count) { $slipway -join ', ' } else { 'none' }))
	$allOpen = @($rows | Where-Object { $_.OpenEngines -ge 1 -and $_.OpenBodies -ge 3 -and $_.MaxSpeed -gt 0.5 }).Count -eq $rows.Count
	$allFreed = @($rows | Where-Object { $_.ClosedEngines -eq 0 -and $_.ClosedBodies -eq 0 -and $_.ClosedManagers -eq 0 -and $_.ClosedClientVessels -eq 0 }).Count -eq $rows.Count
	Add-SlipwayE2ECheck -Run $run -Title "every cycle has live physics while the world is open and the vessels fly" -Condition $allOpen -Detail (($rows | ForEach-Object { "#$($_.Cycle): engines $($_.OpenEngines), bodies $($_.OpenBodies), speed $($_.MaxSpeed)" }) -join '; ') | Out-Null
	Add-SlipwayE2ECheck -Run $run -Title 'after every close no Jolt engine or body is alive and Slipway holds no level or vessel' -Condition $allFreed -Detail (($rows | ForEach-Object { "#$($_.Cycle): engines $($_.ClosedEngines), bodies $($_.ClosedBodies), managers $($_.ClosedManagers), client vessels $($_.ClosedClientVessels)" }) -join '; ') | Out-Null
	# Growth from the second cycle (caches warm) to the last.
	$heapGrowth = $rows[$rows.Count - 1].HeapUsedMb - $rows[1].HeapUsedMb
	$privateGrowth = $rows[$rows.Count - 1].PrivateMb - $rows[1].PrivateMb
	$perCycle = $privateGrowth / [Math]::Max(1, $rows.Count - 2)
	# Heap growth is only a leak of Slipway's if Slipway holds what is retained: follow JFR's paths to GC roots.
	& "$jdk\jcmd.exe" $c.ProcessId JFR.dump name=slipwayleak filename=$jfr 2>&1 | Out-Null
	& "$jdk\jcmd.exe" $c.ProcessId JFR.stop name=slipwayleak 2>&1 | Out-Null
	$samples = ((& "$jdk\jfr.exe" print --events jdk.OldObjectSample --stack-depth 1 $jfr 2>&1) -join "`n") -split 'jdk\.OldObjectSample \{' | Select-Object -Skip 1
	$world = @($samples | Where-Object { $_ -match 'IntegratedServer|ServerLevel|ServerChunkCache|ChunkMap|LevelChunk|ClientLevel' })
	$viaSlipway = @($world | Where-Object { $_ -match 'dev\.timstewart\.slipway|joltjni' })
	$roots = $world | ForEach-Object { [regex]::Match($_, 'description = "([^"]+)"').Groups[1].Value -replace '\[\d+\]', '[n]' } | Group-Object | ForEach-Object { "$($_.Count)x $($_.Name)" }
	$run.Notes.Add(("heap after GC, cycle 2 -> {0}: {1:N1} -> {2:N1} MB ({3:+0.0;-0.0} MB); {4} of {5} old-object samples reach retained worlds, GC roots: {6}" -f $rows.Count, $rows[1].HeapUsedMb, $rows[$rows.Count - 1].HeapUsedMb, $heapGrowth, $world.Count, $samples.Count, $(if ($roots) { $roots -join ', ' } else { 'none' })))
	Add-SlipwayE2ECheck -Run $run -Title 'nothing Slipway holds keeps a closed world alive (JFR paths to GC roots)' -Condition ($samples.Count -gt 0 -and $viaSlipway.Count -eq 0) -Detail ("{0} samples reach retained worlds, {1} of them through Slipway or jolt-jni; roots: {2}; heap after GC grew {3:+0.0;-0.0} MB from cycle 2 to {4}" -f $world.Count, $viaSlipway.Count, $(if ($roots) { $roots -join ', ' } else { 'none' }), $heapGrowth, $rows.Count) | Out-Null
	Add-SlipwayE2ECheck -Run $run -Title 'process memory does not keep growing across world loads' -Condition ($perCycle -lt 64) -Detail ("private memory, cycle 2 -> {0}: {1:N1} -> {2:N1} MB ({3:+0.0;-0.0} MB, {4:N1} MB per cycle)" -f $rows.Count, $rows[1].PrivateMb, $rows[$rows.Count - 1].PrivateMb, $privateGrowth, $perCycle) | Out-Null
} catch {
	Add-SlipwayE2EStep -Run $run -Title 'scenario error' -Detail "$($_.Exception.Message) at $($_.InvocationInfo.PositionMessage)" -Status fail
} finally {
	try { if ((Invoke-SlipwayE2EAgent -Client $c -Verb session) -notlike 'title*') { Invoke-SlipwayE2EAgent -Client $c -Verb disconnect | Out-Null } } catch { }
	# Distant Horizons' world-generation threads sometimes fail to release a pooled array while a world closes quickly after
	# opening (DH-World Gen Thread: "Unable to close Phantom Array ... closed multiple times"); Slipway uses no DH world-gen API.
	$result = Complete-SlipwayE2EScenario -Run $run -Session $session -ServerOffset $serverOffset -ClientOffset $clientOffset -Milestone 'M7' `
		-AlsoIgnore @('Unable to close Phantom Array', 'Null phantom checkout, object is being closed multiple times')
	# The e2e server was stopped for this test; the next scenario starts a fresh session.
	Stop-SlipwayE2ESession | Out-Null
}
$result
