# Scenario leak: one client process opens and closes the same singleplayer world several times. After every close, at
# the title screen and after full garbage collections, no closed world may stay reachable: the live IntegratedServer,
# ServerLevel and ClientLevel counts must not grow from cycle to cycle, and heap after GC must not keep growing. With
# Slipway loaded, no Jolt engine or body may stay alive either.
#
# The mod set is a named configuration, so identical cycles can run with and without each mod (leak-matrix.ps1 runs
# the isolation matrix). Worlds are generated once by the dedicated server and cached in E:\slipway-e2e\worlds:
#   plain   - a Slipway-free world generated by a Fabric-API-only server (loadable by every configuration)
#   vessels - the same terrain with three assembled vessels near spawn (configurations with Slipway)
param(
	[int]$Cycles = 5,
	[ValidateSet('full', 'full-bliss', 'noDH', 'noDH-bliss', 'stackNoSlipway', 'stackNoSlipway-bliss', 'dhOnly', 'vanilla', 'slipwayOnly', 'sodiumIris', 'sodiumIris-bliss')][string]$Config = 'full',
	[ValidateSet('auto', 'vessels', 'plain')][string]$World = 'auto',
	[string]$SlipwayJar,
	[string]$DhJar,
	[switch]$HeapDump,
	[switch]$Jfr,
	# JVM Native Memory Tracking: per-cycle VM.native_memory summaries, to split native growth into JVM categories
	# (threads, metaspace, code cache, direct buffers...) and memory outside the JVM (GL driver, native libraries).
	[switch]$Nmt,
	# Matrix mode: write results here and do not record the run in validation.json.
	[string]$OutDir,
	[switch]$RegenerateWorlds
)
. (Join-Path $PSScriptRoot '_common.ps1')

$repo = Split-Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) -Parent
if (-not $SlipwayJar) { $SlipwayJar = (Get-ChildItem (Join-Path $repo 'build\libs') -Filter 'slipway-fabric-*.jar' | Where-Object { $_.Name -notmatch 'sources' } | Select-Object -First 1).FullName }
$agentJar = (Get-ChildItem (Join-Path $repo 'tools\e2e\agent\build\libs') -Filter 'slipway-e2e-agent-*.jar' | Where-Object { $_.Name -notmatch 'sources' } | Select-Object -First 1).FullName
$jdk = "$env:USERPROFILE\.jdks\jdk-25.0.3+9\bin"
$configs = @{
	'full'           = @('sodium', 'iris', 'dh', 'slipway')
	'full-bliss'     = @('sodium', 'iris', 'dh', 'slipway')
	'noDH-bliss'     = @('sodium', 'iris', 'slipway')
	'stackNoSlipway-bliss' = @('sodium', 'iris', 'dh')
	'sodiumIris-bliss' = @('sodium', 'iris')
	'noDH'           = @('sodium', 'iris', 'slipway')
	'stackNoSlipway' = @('sodium', 'iris', 'dh')
	'sodiumIris'     = @('sodium', 'iris')
	'dhOnly'         = @('dh')
	'vanilla'        = @()
	'slipwayOnly'    = @('slipway')
}
$mods = $configs[$Config]
$withSlipway = $mods -contains 'slipway'
if ($World -eq 'auto') { $World = if ($withSlipway) { 'vessels' } else { 'plain' } }
if ($World -eq 'vessels' -and -not $withSlipway) { throw "Configuration $Config has no Slipway; use -World plain" }
$saveName = "slipway-leak-$World"
# Live instances counted at the title screen; a closed world is reachable if any of these survive a full GC.
$worldClasses = [ordered]@{
	IntegratedServer = 'net.minecraft.client.server.IntegratedServer'
	ServerLevel      = 'net.minecraft.server.level.ServerLevel'
	ClientLevel      = 'net.minecraft.client.multiplayer.ClientLevel'
	LevelChunk       = 'net.minecraft.world.level.chunk.LevelChunk'
	ServerPlayer     = 'net.minecraft.server.level.ServerPlayer'
}

function Wait-Agent([scriptblock]$Until, [int]$Seconds, [string]$What) {
	$deadline = (Get-Date).AddSeconds($Seconds)
	do {
		$value = try { & $Until } catch { $null }
		if ($value) { return $value }
		Start-Sleep -Milliseconds 500
	} while ((Get-Date) -lt $deadline)
	throw "Timed out waiting for $What"
}

function Get-LeakWorld([string]$Kind) {
	# Generates (once) and returns the cached world folder. The server's mods are restored afterwards.
	$cache = Join-Path (Get-SlipwayE2ERoot) "worlds\leak-$Kind"
	if ((Test-Path (Join-Path $cache 'level.dat')) -and -not $RegenerateWorlds) { return $cache }
	Stop-SlipwayE2ESession | Out-Null
	$serverMods = Join-Path (Get-SlipwayE2EServerDir) 'mods'
	$saved = Join-Path (Get-SlipwayE2ERoot) 'worlds\server-mods-backup'
	Remove-Item $saved -Recurse -Force -ErrorAction SilentlyContinue
	New-Item -ItemType Directory -Force $saved | Out-Null
	Get-ChildItem $serverMods -Filter *.jar | Copy-Item -Destination $saved
	try {
		if ($Kind -eq 'plain') { Set-SlipwayE2EServerMods | Out-Null } else { Set-SlipwayE2EServerMods -SlipwayJar $SlipwayJar | Out-Null }
		$name = "leak-$Kind"
		New-SlipwayE2EWorld -Name $name | Out-Null
		$server = Start-SlipwayE2EServer -World $name
		try {
			Send-SlipwayE2ERcon -Command 'forceload add -48 -16 48 48' | Out-Null
			Start-Sleep -Seconds 3
			Send-SlipwayE2ERcon -Command 'fill -8 99 -8 8 99 -2 minecraft:glass' | Out-Null
			if ($Kind -eq 'vessels') {
				foreach ($k in 0..2) {
					$x = -14 + 14 * $k; $z = 16
					Send-SlipwayE2ERcon -Command ("fill {0} 99 {1} {2} 99 {3} minecraft:oak_planks" -f ($x - 2), ($z - 2), ($x + 2), ($z + 2)) | Out-Null
					Send-SlipwayE2ERcon -Command ("setblock {0} 100 {1} slipway:helm[facing=north]" -f $x, $z) | Out-Null
					Send-SlipwayE2ERcon -Command ("setblock {0} 100 {1} minecraft:chest" -f ($x + 1), ($z + 1)) | Out-Null
					Invoke-SlipwayE2EAssembleCommand -X $x -Y 100 -Z $z | Out-Null
				}
			}
			foreach ($cmd in 'forceload remove all', 'time set noon', 'gamerule advance_time false', 'weather clear', 'gamerule advance_weather false', 'save-all flush') {
				Send-SlipwayE2ERcon -Command $cmd | Out-Null
			}
			Start-Sleep -Seconds 2
		} finally {
			Stop-SlipwayE2EServer -Server $server | Out-Null
		}
		Remove-Item $cache -Recurse -Force -ErrorAction SilentlyContinue
		New-Item -ItemType Directory -Force (Split-Path $cache) | Out-Null
		Copy-Item (Join-Path (Get-SlipwayE2EServerDir) $name) $cache -Recurse
		Remove-Item (Join-Path $cache 'session.lock') -Force -ErrorAction SilentlyContinue
		@'
import sys, nbtlib
f = nbtlib.load(sys.argv[1])
d = f["Data"]
d["allowCommands"] = nbtlib.Byte(1)
d["GameType"] = nbtlib.Int(1)
d["LevelName"] = nbtlib.String(sys.argv[2])
f.save()
'@ | python - (Join-Path $cache 'level.dat') "Slipway leak test ($Kind)" | Out-Null
	} finally {
		Get-ChildItem $serverMods -Filter *.jar | Remove-Item -Force
		Get-ChildItem $saved -Filter *.jar | Copy-Item -Destination $serverMods
	}
	$cache
}

function Read-Histogram([string]$Path) {
	$map = @{}
	foreach ($line in Get-Content $Path) {
		if ($line -match '^\s*\d+:\s+(\d+)\s+(\d+)\s+(\S+)') { $map[$matches[3]] = @([long]$matches[1], [long]$matches[2]) }
	}
	$map
}

function Read-Nmt([string]$Path) {
	# Committed MB per NMT category, plus the live thread count.
	$map = [ordered]@{}
	foreach ($line in Get-Content $Path) {
		if ($line -match '^-\s+(.+?) \(reserved=(\d+)KB, committed=(\d+)KB\)') { $map[$matches[1].Trim()] = [Math]::Round([double]$matches[3] / 1024, 1) }
		elseif ($line -match '\(threads #(\d+)\)') { $map['threads'] = [int]$matches[1] }
		elseif ($line -match '^Total: reserved=(\d+)KB, committed=(\d+)KB') { $map['Total'] = [Math]::Round([double]$matches[2] / 1024, 1) }
	}
	$map
}

# 1. Worlds, mods, options.
$worldDir = Get-LeakWorld $World
Stop-SlipwayE2ESession | Out-Null
$modList = Set-SlipwayE2EModSet -Mods $mods -SlipwayJar $SlipwayJar -DhJar $DhJar -AgentJar $agentJar
Set-SlipwayE2EOptions -RenderDistance 10
# '-bliss' configurations run with Iris and the Bliss shader pack on.
Set-SlipwayE2EShaders -Enabled ($Config -like '*-bliss')
$gameDir = Join-Path (Get-SlipwayE2EInstanceDir) '.minecraft'
$dest = Join-Path $gameDir "saves\$saveName"
if (Test-Path $dest) { Remove-Item $dest -Recurse -Force }
Copy-Item $worldDir $dest -Recurse

if ($OutDir) {
	New-Item -ItemType Directory -Force $OutDir | Out-Null
	$run = [pscustomobject]@{ Name = "leak-$Config"; Id = (Split-Path $OutDir -Leaf); Directory = $OutDir; Steps = [System.Collections.Generic.List[object]]::new(); StartedAt = Get-Date
		Notes = [System.Collections.Generic.List[string]]::new(); JarSha256 = '' }
} else {
	$run = New-SlipwayE2ERun -Name 'leak'
}
$run.JarSha256 = if ($withSlipway) { (Get-FileHash $SlipwayJar -Algorithm SHA256).Hash } else { '' }
$run.Notes.Add("configuration $Config, world $World, $Cycles cycles; mods: " + (($modList | ForEach-Object { $_.Jar }) -join ', '))

function Stop-PrismLauncher {
	# Prism caches instance settings while it runs, so JVM-argument changes need it closed. Refuses while a game runs.
	. "$HOME\.copilot\skills\minecraft-window-automation\scripts\MinecraftWindowAutomation.ps1"
	$games = @(Get-CimInstance Win32_Process -Filter "Name='javaw.exe' or Name='java.exe'" | Where-Object { $_.CommandLine -match 'PrismLauncher' })
	if ($games.Count) { throw "A Prism game is running (pid $($games[0].ProcessId)); not closing Prism" }
	foreach ($p in @(Get-Process -Name prismlauncher -ErrorAction SilentlyContinue)) {
		try { Close-CopilotWindowGracefully -ProcessId $p.Id -TimeoutSeconds 30 | Out-Null } catch { }
		if (-not $p.WaitForExit(30000)) { Stop-Process -Id $p.Id -Force }
	}
}

$c = $null
$rows = [System.Collections.Generic.List[object]]::new()
$instanceCfg = Join-Path (Get-SlipwayE2EInstanceDir) 'instance.cfg'
$instanceCfgBackup = Get-Content $instanceCfg -Raw
try {
	if ($Nmt) {
		Stop-PrismLauncher
		# Prism writes the value quoted (JvmArgs="..."); the flag must go inside the quotes.
		$cfgLines = Get-Content $instanceCfg | ForEach-Object {
			if ($_ -match '^JvmArgs="(.*)"$' -and $matches[1] -notmatch 'NativeMemoryTracking') { 'JvmArgs="' + $matches[1] + ' -XX:NativeMemoryTracking=summary"' }
			elseif ($_ -match '^JvmArgs=([^"].*)$' -and $matches[1] -notmatch 'NativeMemoryTracking') { 'JvmArgs=' + $matches[1] + ' -XX:NativeMemoryTracking=summary' }
			else { $_ }
		}
		Set-Content $instanceCfg $cfgLines -Encoding UTF8
	}
	# 2. A client at the title screen (no server).
	$c = Start-SlipwayE2EClient
	if ($Nmt) {
		$cmd = (Get-CimInstance Win32_Process -Filter "ProcessId=$($c.ProcessId)").CommandLine
		if ($cmd -notmatch '\s-XX:NativeMemoryTracking=summary\s' -or $cmd -notmatch '\s--enable-native-access=ALL-UNNAMED\s') { throw "The game's JVM arguments are not as configured (NMT and native access): $($cmd.Substring(0, [Math]::Min(300, $cmd.Length)))" }
	}
	$clientOffset = 0
	Wait-Agent { (Invoke-SlipwayE2EAgent -Client $c -Verb session -TimeoutSeconds 5) -like 'title*' } 300 'the title screen' | Out-Null
	$clientOffset = Get-SlipwayE2ELogOffset -LogPath $c.ClientLog
	$jfrFile = Join-Path $run.Directory 'leak.jfr'
	if ($Jfr) { & "$jdk\jcmd.exe" $c.ProcessId JFR.start name=slipwayleak settings=profile path-to-gc-roots=true 2>&1 | Out-Null }

	# 3. Identical cycles: open, settle, (fly the vessels), close, full GC, count what is still alive.
	for ($cycle = 1; $cycle -le $Cycles; $cycle++) {
		Invoke-SlipwayE2EAgent -Client $c -Verb openworld -Argument $saveName | Out-Null
		Wait-Agent { $w = Invoke-SlipwayE2EAgent -Client $c -Verb session; $sc = Invoke-SlipwayE2EAgent -Client $c -Verb screen; ($w -like 'world singleplayer*') -and $sc -eq 'none' } 180 'the world to open' | Out-Null
		Invoke-SlipwayE2EAgent -Client $c -Verb chat -Argument '/tp @s 0 100.5 -5' | Out-Null
		$terrain = Wait-SlipwayE2ETerrain -Client $c -StableMilliseconds 1000 -TimeoutSeconds 60
		$open = $null; $flying = $null; $speeds = @()
		if ($World -eq 'vessels') {
			Wait-Agent { $v = [string](Invoke-SlipwayE2EAgent -Client $c -Verb slipway -Argument 'vessels'); ([regex]::Matches($v, 'ready=true').Count -ge 3) } 60 'the vessels to arrive' | Out-Null
			$open = Invoke-SlipwayE2EAgent -Client $c -Verb slipway -Argument 'natives'
			foreach ($m in [regex]::Matches([string](Invoke-SlipwayE2EAgent -Client $c -Verb slipway -Argument 'vessels'), '#(\d+) ')) {
				Invoke-SlipwayE2EAgent -Client $c -Verb chat -Argument "/slipway control $($m.Groups[1].Value) 0.3 0 0.1 0 0.4 0 200" | Out-Null
			}
		}
		Start-Sleep -Seconds 5
		if ($World -eq 'vessels') {
			$flying = Invoke-SlipwayE2EAgent -Client $c -Verb slipway -Argument 'natives'
			$speeds = @([regex]::Matches([string](Invoke-SlipwayE2EAgent -Client $c -Verb slipway -Argument 'vessels'), 'speed=([\d.]+)') | ForEach-Object { [double]$_.Groups[1].Value })
		}
		Invoke-SlipwayE2EAgent -Client $c -Verb disconnect | Out-Null
		Wait-Agent { (Invoke-SlipwayE2EAgent -Client $c -Verb session) -like 'title*' } 120 'the world to close' | Out-Null
		Start-Sleep -Seconds 3
		$closed = if ($withSlipway) { Invoke-SlipwayE2EAgent -Client $c -Verb slipway -Argument 'natives' } else { '' }
		$mem = [string](Invoke-SlipwayE2EAgent -Client $c -Verb mem)
		$histogram = Join-Path $run.Directory ("histogram-cycle{0}.txt" -f $cycle)
		& "$jdk\jcmd.exe" $c.ProcessId GC.class_histogram 2>&1 | Set-Content $histogram
		$h = Read-Histogram $histogram
		$p = Get-Process -Id $c.ProcessId
		$row = [ordered]@{ Cycle = $cycle; TerrainSettled = $terrain
			HeapUsedMb = [double]([regex]::Match($mem, 'heapUsedMb=([\d.]+)').Groups[1].Value)
			HistogramMb = [Math]::Round((($h.Values | ForEach-Object { $_[1] }) | Measure-Object -Sum).Sum / 1MB, 1)
			HeapCommittedMb = [double]([regex]::Match($mem, 'heapCommittedMb=([\d.]+)').Groups[1].Value)
			PrivateMb = [Math]::Round($p.PrivateMemorySize64 / 1MB, 1)
			Threads = $p.Threads.Count
			Handles = $p.HandleCount }
		# Live Java threads by name (numbers folded), to attribute thread growth to its owner.
		$threadFile = Join-Path $run.Directory ("threads-cycle{0}.txt" -f $cycle)
		& "$jdk\jcmd.exe" $c.ProcessId Thread.print 2>&1 | Set-Content $threadFile
		$groups = @{}
		foreach ($line in Get-Content $threadFile) {
			if ($line -match '^"([^"]+)"') { $name = $matches[1] -replace '\d+', '#'; $groups[$name] = 1 + [int]$groups[$name] }
		}
		$row.ThreadGroups = $groups
		# ZGC maps the Java heap as shared memory on Windows, so the process's private bytes do not include the heap:
		# they are its native memory (thread stacks, metaspace, code cache, direct buffers, GL driver, native libraries).
		$row.NativeMb = $row.PrivateMb
		if ($Nmt) {
			$nmtFile = Join-Path $run.Directory ("nmt-cycle{0}.txt" -f $cycle)
			& "$jdk\jcmd.exe" $c.ProcessId VM.native_memory summary 2>&1 | Set-Content $nmtFile
			$n = Read-Nmt $nmtFile
			$row.NmtJvmNonHeapMb = [Math]::Round($n['Total'] - $n['Java Heap'], 1)
			$row.NmtOutsideJvmMb = [Math]::Round($row.PrivateMb - $row.NmtJvmNonHeapMb, 1)
			foreach ($k in 'Class', 'Thread', 'Code', 'GC', 'Compiler', 'Internal', 'Other', 'Symbol', 'Metaspace', 'Arena Chunk', 'Module', 'Serviceability', 'Native Memory Tracking') {
				if ($n.Contains($k)) { $row["Nmt$($k -replace '\s', '')Mb"] = $n[$k] }
			}
			$row.NmtThreads = $n['threads']
		}
		foreach ($k in $worldClasses.Keys) { $row[$k] = if ($h.ContainsKey($worldClasses[$k])) { $h[$worldClasses[$k]][0] } else { 0 } }
		if ($withSlipway) {
			foreach ($pair in @(@('Open', $open), @('Flying', $flying), @('Closed', $closed))) {
				$m = [regex]::Match([string]$pair[1], 'engines=(\d+) bodies=(\d+) managers=(\d+) clientVessels=(\d+)')
				$row["$($pair[0])Engines"] = if ($m.Success) { [int]$m.Groups[1].Value } else { $null }
				$row["$($pair[0])Bodies"] = if ($m.Success) { [int]$m.Groups[2].Value } else { $null }
				if ($pair[0] -eq 'Closed') { $row.ClosedManagers = if ($m.Success) { [int]$m.Groups[3].Value } else { $null }; $row.ClosedClientVessels = if ($m.Success) { [int]$m.Groups[4].Value } else { $null } }
			}
			$row.MaxSpeed = ($speeds | Measure-Object -Maximum).Maximum
		}
		$rows.Add([pscustomobject]$row)
		$run.Notes.Add(("cycle {0}: heap after GC {1:N1} MB (histogram {2:N1} MB), private {3:N1} MB; live at the title screen: " -f $cycle, $row.HeapUsedMb, $row.HistogramMb, $row.PrivateMb) +
			(($worldClasses.Keys | ForEach-Object { "$_ $($row[$_])" }) -join ', '))
	}
	$rows | ConvertTo-Json | Set-Content (Join-Path $run.Directory 'leak.json')

	# 4. Per-class growth between the second cycle (caches warm) and the last.
	$h2 = Read-Histogram (Join-Path $run.Directory 'histogram-cycle2.txt')
	$hN = Read-Histogram (Join-Path $run.Directory ("histogram-cycle{0}.txt" -f $Cycles))
	$growth = foreach ($k in $hN.Keys) {
		$before = if ($h2.ContainsKey($k)) { $h2[$k] } else { @(0, 0) }
		[pscustomobject]@{ Class = $k; Instances = $hN[$k][0] - $before[0]; Mb = [Math]::Round(($hN[$k][1] - $before[1]) / 1MB, 2) }
	}
	$growth | Sort-Object Mb -Descending | Select-Object -First 40 | Format-Table -AutoSize | Out-String -Width 220 | Set-Content (Join-Path $run.Directory 'histogram-growth.txt')
	$slipwayGrowth = @($growth | Where-Object { $_.Class -match 'slipway|joltjni' -and $_.Instances -gt 0 } | Sort-Object Instances -Descending | Select-Object -First 10 | ForEach-Object { "$($_.Class) +$($_.Instances)" })
	$run.Notes.Add("largest growth, cycle 2 -> ${Cycles}: " + ((($growth | Sort-Object Mb -Descending | Select-Object -First 6) | ForEach-Object { "$($_.Class) +$($_.Mb) MB (+$($_.Instances))" }) -join '; '))
	$run.Notes.Add("Slipway/jolt classes that grew: " + $(if ($slipwayGrowth.Count) { $slipwayGrowth -join ', ' } else { 'none' }))

	if ($HeapDump) {
		$dumpDir = Join-Path (Get-SlipwayE2ERoot) 'heap'
		New-Item -ItemType Directory -Force $dumpDir | Out-Null
		$dump = Join-Path $dumpDir ("{0}-{1}.hprof" -f (Split-Path (Split-Path $run.Directory) -Leaf), $run.Id)
		& "$jdk\jcmd.exe" $c.ProcessId GC.heap_dump $dump 2>&1 | Out-Null
		$run.Notes.Add($(if (Test-Path $dump) { "heap dump (live objects, after cycle $Cycles): $dump" } else { "heap dump FAILED: $dump was not written" }))
	}
	if ($Jfr) {
		& "$jdk\jcmd.exe" $c.ProcessId JFR.dump name=slipwayleak filename=$jfrFile 2>&1 | Out-Null
		& "$jdk\jcmd.exe" $c.ProcessId JFR.stop name=slipwayleak 2>&1 | Out-Null
	}

	# 5. Checks.
	$allOpened = $rows.Count -eq $Cycles
	Add-SlipwayE2ECheck -Run $run -Title "all $Cycles cycles opened and closed the world" -Condition $allOpened -Detail "$($rows.Count) cycles" | Out-Null
	if ($World -eq 'vessels') {
		$live = @($rows | Where-Object { $_.OpenEngines -ge 1 -and $_.OpenBodies -ge 3 -and $_.MaxSpeed -gt 0.5 }).Count -eq $rows.Count
		Add-SlipwayE2ECheck -Run $run -Title 'every cycle has live physics while the world is open and the vessels fly' -Condition $live -Detail (($rows | ForEach-Object { "#$($_.Cycle): engines $($_.OpenEngines), bodies $($_.OpenBodies), speed $($_.MaxSpeed)" }) -join '; ') | Out-Null
	}
	if ($withSlipway) {
		$freed = @($rows | Where-Object { $_.ClosedEngines -eq 0 -and $_.ClosedBodies -eq 0 -and $_.ClosedManagers -eq 0 -and $_.ClosedClientVessels -eq 0 }).Count -eq $rows.Count
		Add-SlipwayE2ECheck -Run $run -Title 'after every close no Jolt engine or body is alive and Slipway holds no level or vessel' -Condition $freed -Detail (($rows | ForEach-Object { "#$($_.Cycle): engines $($_.ClosedEngines), bodies $($_.ClosedBodies), managers $($_.ClosedManagers), client vessels $($_.ClosedClientVessels)" }) -join '; ') | Out-Null
	}
	# Strict: a closed world must not stay reachable, so the counts may not grow from one cycle to the next.
	$first = $rows[0]
	$grew = @(foreach ($r in $rows) { foreach ($k in 'IntegratedServer', 'ServerLevel', 'ClientLevel') { if ($r.$k -gt $first.$k) { "cycle $($r.Cycle) $k $($r.$k) > $($first.$k)" } } })
	Add-SlipwayE2ECheck -Run $run -Title 'no closed world stays reachable: live IntegratedServer, ServerLevel and ClientLevel counts do not grow' -Condition ($grew.Count -eq 0) `
		-Detail ((($rows | ForEach-Object { "#$($_.Cycle): servers $($_.IntegratedServer), server levels $($_.ServerLevel), client levels $($_.ClientLevel), chunks $($_.LevelChunk)" }) -join '; ') + $(if ($grew.Count) { ' | grew: ' + ($grew -join ', ') } else { '' })) | Out-Null
	$heapPerCycle = ($rows[$rows.Count - 1].HeapUsedMb - $rows[1].HeapUsedMb) / [Math]::Max(1, $rows.Count - 2)
	Add-SlipwayE2ECheck -Run $run -Title 'heap after GC does not keep growing (under 16 MB per cycle from cycle 2)' -Condition ($heapPerCycle -lt 16) `
		-Detail ("heap after GC: " + (($rows | ForEach-Object { "{0:N1}" -f $_.HeapUsedMb }) -join ' -> ') + (" MB; {0:+0.0;-0.0} MB per cycle" -f $heapPerCycle)) | Out-Null
	$privatePerCycle = ($rows[$rows.Count - 1].PrivateMb - $rows[1].PrivateMb) / [Math]::Max(1, $rows.Count - 2)
	$nativePerCycle = $privatePerCycle
	$run.Notes.Add(("process threads: " + (($rows | ForEach-Object { $_.Threads }) -join ' -> ') + "; handles: " + (($rows | ForEach-Object { $_.Handles }) -join ' -> ')))
	# Thread groups that grew from cycle 2 to the last. Netty's local event-loop group is one static pool of at most
	# 2 x processors threads started lazily round-robin (vanilla EventLoopGroupHolder.LOCAL), so it is bounded.
	$g2 = $rows[1].ThreadGroups; $gN = $rows[$rows.Count - 1].ThreadGroups
	$threadGrowth = @(foreach ($k in $gN.Keys) { $d = $gN[$k] - [int]$g2[$k]; if ($d -gt 0) { [pscustomobject]@{ Group = $k; Growth = $d; Count = $gN[$k] } } })
	$run.Notes.Add("thread groups that grew from cycle 2: " + $(if ($threadGrowth.Count) { ($threadGrowth | Sort-Object Growth -Descending | ForEach-Object { "$($_.Group) +$($_.Growth) (now $($_.Count))" }) -join '; ' } else { 'none' }))
	$nettyCap = 2 * [Environment]::ProcessorCount
	# JIT compiler threads are added and retired by the JVM itself, within its fixed compiler count.
	$unbounded = @($threadGrowth | Where-Object { -not ($_.Group -like 'Netty Local IO #*' -and $_.Count -le $nettyCap) -and $_.Group -notlike 'C# CompilerThread#' })
	Add-SlipwayE2ECheck -Run $run -Title "no thread group grows across world loads (except Netty's bounded local event loops, at most $nettyCap, and JIT compiler threads)" -Condition ($unbounded.Count -eq 0) `
		-Detail $(if ($unbounded.Count) { ($unbounded | ForEach-Object { "$($_.Group) +$($_.Growth)" }) -join '; ' } else { 'none grew' }) | Out-Null
	if ($Nmt) {
		$run.Notes.Add(("NMT JVM non-heap committed: " + (($rows | ForEach-Object { '{0:N0}' -f $_.NmtJvmNonHeapMb }) -join ' -> ') + " MB; outside the JVM (private - NMT non-heap): " + (($rows | ForEach-Object { '{0:N0}' -f $_.NmtOutsideJvmMb }) -join ' -> ') + ' MB'))
		foreach ($k in 'NmtClassMb', 'NmtThreadMb', 'NmtCodeMb', 'NmtGCMb', 'NmtOtherMb', 'NmtInternalMb', 'NmtSymbolMb', 'NmtMetaspaceMb', 'NmtThreads') {
			$run.Notes.Add(("  {0}: {1}" -f $k, (($rows | ForEach-Object { $_.$k }) -join ' -> ')))
		}
	}
	Add-SlipwayE2ECheck -Run $run -Title 'native memory (process private bytes; the ZGC heap is not in them) does not keep growing across world loads (under 64 MB per cycle from cycle 2; not applied with a shader pack on, see DESIGN.md)' -Condition ($nativePerCycle -lt 64 -or $Config -like '*-bliss') `
		-Detail ("private memory: " + (($rows | ForEach-Object { "{0:N0}" -f $_.PrivateMb }) -join ' -> ') + (" MB; {0:+0.0;-0.0} MB per cycle" -f $privatePerCycle)) | Out-Null
} catch {
	Add-SlipwayE2EStep -Run $run -Title 'scenario error' -Detail "$($_.Exception.Message) at $($_.InvocationInfo.PositionMessage)" -Status fail
} finally {
	if ($c) {
		try { if ((Invoke-SlipwayE2EAgent -Client $c -Verb session -TimeoutSeconds 10) -notlike 'title*') { Invoke-SlipwayE2EAgent -Client $c -Verb disconnect | Out-Null } } catch { }
		# Distant Horizons' world-generation threads sometimes fail to release a pooled array while a world closes quickly
		# after opening (DH-World Gen Thread: "Unable to close Phantom Array ... closed multiple times").
		$problems = @(Get-SlipwayE2ELogProblems -LogPath $c.ClientLog -Offset $clientOffset -AlsoIgnore @('Unable to close Phantom Array', 'Null phantom checkout, object is being closed multiple times'))
		Add-SlipwayE2ECheck -Run $run -Title 'client log has no errors, exceptions or Slipway warnings' -Condition ($problems.Count -eq 0) -Detail (($problems | Select-Object -First 5) -join ' / ') | Out-Null
		Read-SlipwayE2ELogSince -LogPath $c.ClientLog -Offset $clientOffset | Set-Content (Join-Path $run.Directory 'client-log-excerpt.txt') -Encoding UTF8
		if (-not (Stop-SlipwayE2EClient -Client $c -TimeoutSeconds 90)) {
			# a test-instance game this scenario started (for example one that never finished loading)
			Stop-Process -Id $c.ProcessId -Force -ErrorAction SilentlyContinue
			$run.Notes.Add("the client did not close within 90 s and was stopped (pid $($c.ProcessId))")
		}
	}
	if ($Nmt) {
		try { Stop-PrismLauncher } catch { Write-Warning $_.Exception.Message }
	}
	Set-Content $instanceCfg $instanceCfgBackup -NoNewline -Encoding UTF8
	$result = Save-SlipwayE2EReport -Run $run
	if (-not $OutDir) { Add-SlipwayValidation -Run $run -Result $result -Milestone 'M7' | Out-Null }
	Write-Host "Scenario leak ($Config, $World): $result -> $($run.Directory)"
}
[pscustomobject]@{ Result = $result; Directory = $run.Directory; Rows = $rows; Config = $Config; World = $World }
